Cache FileEngine.php possible Exception
Avoid possible Exception with unlink.

I got the following Exception because of some weird stuff in my servers filesystem:

Exception: unlink(): Argument #1 ($filename) must be of type string, bool given
In [/home/wotanabx/webseiten/wow-das/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 227]
[TypeError] unlink(): Argument #1 ($filename) must be of type string, bool given in /home/wotanabx/webseiten/wow-das/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php on line 227